M48
; DRILL file {KiCad (6.0.4)} date Wed Apr  6 16:34:32 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-04-06T16:34:32+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X4.575Y-3.2091
X4.575Y-3.4366
T2
X4.5039Y-4.0945
X7.0394Y-2.378
X7.0394Y-4.0945
T0
M30
