M48
; DRILL file {KiCad 6.0.4-1.fc35} date 2022-04-06T21:04:06 IDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-04-06T21:04:06+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.4-1.fc35
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X4.575Y-3.2091
X4.575Y-3.4366
T2
X4.5039Y-4.0945
X7.0394Y-2.378
X7.0394Y-4.0945
T0
M30
